// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "ihp-backend/react";

function App(Props) {
  return React.createElement(React$1.ThinBackend, {
              children: React.createElement("div", undefined, "Hello IHP Backend World!")
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
