// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "./Task.bs.js";
import * as React from "react";
import * as NewTask from "./NewTask.bs.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as IhpBackend from "ihp-backend";
import * as React$1 from "ihp-backend/react";

function App(Props) {
  var tasks = React$1.useQuery(IhpBackend.query("tasks").orderBy("createdAt").filterWhere("title", "test").limit(10));
  return React.createElement(React$1.IHPBackend, {
              children: null
            }, (tasks == null) ? "loading" : Belt_Array.map(tasks, (function (task) {
                      return React.createElement(Task.make, {
                                  task: task,
                                  key: task.id
                                });
                    })), React.createElement("hr", undefined), React.createElement(NewTask.make, {}));
}

var make = App;

export {
  make ,
  
}
/* Task Not a pure module */
